//
//  ViewController.swift
//  leavesOfGrass
//
//  Created by Julia on 10/8/16.
//  Copyright © 2016 JuliaGeist. All rights reserved.
//

import UIKit
import Foundation

class ViewController: UIViewController {
    
    let arrayOfPoemIndexes = [
        "whoever-you-are-holding-me",
        "spontaneous-me",
        "after-the-supper-and-talk",
        "world-take-good-notice",
        "youth-day-old-age-and",
        "the-dead-tenor",
        "as-i-watch-the-ploughman",
        "book-iv.-children-of",
        "the-dying-veteran",
        "visord",
        "as-they-draw-to-a",
        "a-sight-in-camp-in",
        "the-prairie-states",
        "red-jacket-(from-aloft)",
        "song-of-the-answerer",
        "not-youth-pertains-to-me",
        "the-dismantled-ship",
        "a-song-for-occupations",
        "to-a-president",
        "bookxxxv.-goodbye-my-fancy",
        "germs",
        "an-evening-lull",
        "from-montauk-point",
        "after-the-dazzle-of-day",
        "among-the-multitude",
        "the-ship-starting",
        "laws-for-creations",
        "cavalry-crossing-a-ford",
        "reversals",
        "the-last-invocation",
        "on-journeys-through-the-states",
        "osceola",
        "city-of-orgies",
        "fast-anchord-eternal-o-love",
        "the-wounddresser",
        "race-of-veterans",
        "by-blue-ontarios-shore",
        "the-pallid-wreath",
        "give-me-the-splendid-silent",
        "book-xviii",
        "beginners",
        "a-persian-lesson",
        "book-xxxii.-from-noon",
        "old-salt-kossabone",
        "to-a-historian",
        "a-voice-from-death",
        "book-xxiii",
        "a-font-of-type",
        "to-the-pending-year",
        "lingering-last-drops",
        "book-xix.-seadrift",
        "small-the-theme-of-my",
        "i-hear-america-singing",
        "thicksprinkled-bunting",
        "kosmos",
        "look-down-fair-moon",
        "a-song-of-joys",
        "excelsior",
        "to-a-pupil",
        "goodbye-my-fancy",
        "book-x",
        "thou-mother-with-thy-equal",
        "orange-buds-by-mail-from",
        "of-him-i-love-day",
        "there-was-a-child-went",
        "book-xv",
        "a-farm-picture",
        "i-am-he-that-aches",
        "we-two-how-long-we",
        "unfolded-out-of-the-folds",
        "a-broadway-pageant",
        "a-noiseless-patient-spider",
        "this-compost",
        "book-xxxi",
        "as-toilsome-i-wanderd-virginias",
        "mother-and-babe",
        "sparkles-from-the-wheel",
        "weave-in-my-hardy-life",
        "roaming-in-thought-[after-reading",
        "i-dreamd-in-a-dream",
        "beautiful-women",
        "beat-beat-drums",
        "vocalism",
        "me-imperturbe",
        "a-leaf-for-hand-in",
        "lo-victress-on-the-peaks",
        "all-is-truth",
        "book-xi",
        "to-a-stranger",
        "our-old-feuillage",
        "beginning-my-studies",
        "with-all-thy-gifts",
        "ashes-of-soldiers",
        "going-somewhere",
        "spirit-that-formd-this-scene",
        "as-adam-early-in-the",
        "old-ages-ship-crafty",
        "camps-of-green",
        "book-xxvi",
        "to-think-of-time",
        "an-army-corps-on-the",
        "when-lilacs-last-in-the",
        "now-finale-to-the-shore",
        "the-sobbing-of-the-bells",
        "book-xxxiii.-songs-of",
        "fancies-at-navesink",
        "mirages",
        "book-vi",
        "broadway",
        "this-dust-was-once-the",
        "true-conquerors",
        "continuities",
        "as-i-ponderd-in-silence",
        "year-of-meteors-[185960",
        "i-sing-the-body-electric",
        "book-xiv",
        "while-not-the-past-forgetting",
        "election-day-november-1884",
        "song-of-myself",
        "portals",
        "the-first-dandelion",
        "what-best-i-see-in",
        "from-far-dakotas-canyons",
        "thou-orb-aloft-fulldazzling",
        "thoughts",
        "the-world-below-the-brine",
        "city-of-ships",
        "over-the-carnage-rose-prophetic",
        "not-heaving-from-my-ribbd",
        "to-foreign-lands",
        "salut-au-monde",
        "to-one-shortly-to-die",
        "i-saw-old-general-at",
        "prayer-of-columbus",
        "spirit-whose-work-is-done",
        "a-glimpse",
        "in-paths-untrodden",
        "the-sleepers",
        "how-solemn-as-one-by",
        "warble-for-lilactime",
        "savantism",
        "mediums",
        "you-lingering-sparse-leaves-of",
        "hast-never-come-to-thee",
        "whispers-of-heavenly-death",
        "thought",
        "the-return-of-the-heroes",
        "trickle-drops",
        "tests",
        "not-meagre-latent-boughs-alone",
        "roots-and-leaves-themselves-alone",
        "song-for-all-seas-all",
        "here-the-frailest-leaves-of",
        "assurances",
        "a-march-in-the-ranks",
        "virginiathe-west",
        "proud-music-of-the-storm",
        "a-promise-to-california",
        "to-you",
        "onesself-i-sing",
        "year-that-trembled-and-reeld",
        "book-xvii.-birds-of",
        "yet-yet-ye-downcast-hours",
        "out-of-mays-shows-selected",
        "first-o-songs-for-a",
        "pioneers-o-pioneers",
        "grand-is-the-seen",
        "these-i-singing-in-spring",
        "book-xii",
        "out-of-the-rolling-ocean",
        "to-rich-givers",
        "that-music-always-round-me",
        "as-i-lay-with-my",
        "book-xxvii",
        "today-and-thee",
        "book-xxx.-whispers-of",
        "a-carol-closing-sixtynine",
        "come-up-from-the-fields",
        "for-you-o-democracy",
        "out-of-the-cradle-endlessly",
        "gliding-oer-all",
        "death-of-general-grant",
        "miracles",
        "to-the-east-and-to",
        "life-and-death",
        "the-commonplace",
        "eidolons",
        "that-shadow-my-likeness",
        "stronger-lessons",
        "book-xxiv.-autumn-rivulets",
        "what-am-i-after-all",
        "hushd-be-the-camps-today",
        "pensive-on-her-dead-gazing",
        "the-calming-thought-of-all",
        "with-antecedents",
        "what-ship-puzzled-at-sea",
        "book-viii",
        "book-iii",
        "unnamed-land",
        "unseen-buds",
        "the-untold-want",
        "the-oxtamer",
        "shut-not-your-doors",
        "to-the-garden-the-world",
        "when-i-read-the-book",
        "scented-herbage-of-my-breast",
        "poets-to-come",
        "my-picturegallery",
        "now-precedent-songs-farewell",
        "full-of-life-now",
        "paumanok",
        "song-of-the-open-road",
        "europe-[the-72d-and-73d",
        "as-at-thy-portals-also",
        "facing-west-from-californias-shores",
        "who-learns-my-lesson-complete",
        "native-moments",
        "out-from-behind-this-mask",
        "as-the-time-draws-nigh",
        "reconciliation",
        "tears",
        "i-heard-you-solemnsweet-pipes",
        "so-long",
        "o-star-of-france-[187071]",
        "o-captain-my-captain",
        "on-on-the-same-ye",
        "bivouac-on-a-mountain-side",
        "spain-187374",
        "interpolation-sounds",
        "book-xx.-by-the",
        "the-torch",
        "aboard-at-a-ships-helm",
        "l.-of-g.s-purport",
        "italian-music-in-dakota",
        "song-of-prudence",
        "adieu-to-a-soldier",
        "not-the-pilot",
        "sounds-of-the-winter",
        "offerings",
        "to-a-common-prostitute",
        "myself-and-mine",
        "after-the-seaship",
        "twilight",
        "song-of-the-universal",
        "a-paumanok-picture",
        "rise-o-days-from-your",
        "to-a-western-boy",
        "dirge-for-two-veterans",
        "transpositions",
        "ethiopia-saluting-the-colors",
        "the-singer-in-the-prison",
        "to-a-certain-cantatrice",
        "to-a-locomotive-in-winter",
        "eighteen-sixtyone",
        "the-prairiegrass-dividing",
        "book-xxviii",
        "ah-poverties-wincings-and-sulky",
        "for-him-i-sing",
        "mannahatta",
        "to-those-whove-faild",
        "life",
        "to-the-states",
        "book-i.-inscriptions",
        "old-wardreams",
        "to-the-manofwarbird",
        "wandering-at-morn",
        "the-wallabout-martyrs",
        "twenty-years",
        "book-xxix",
        "the-runner",
        "the-voice-of-the-rain",
        "to-a-foild-european-revolutionaire",
        "i-was-looking-a-long",
        "as-the-greeks-signal-flame",
        "from-pentup-aching-rivers",
        "what-think-you-i-take",
        "when-i-peruse-the-conquerd",
        "faces",
        "to-get-the-final-lilt",
        "chanting-the-square-deific",
        "book-ix",
        "not-heat-flames-up-and",
        "the-mystic-trumpeter",
        "book-xxxiv.-sands-at",
        "passage-to-india",
        "the-bravest-soldiers",
        "book-ii",
        "years-of-the-modern",
        "pensive-and-faltering",
        "when-the-fullgrown-poet-came",
        "i-hear-it-was-charged",
        "thanks-in-old-age",
        "when-i-heard-the-learnd",
        "no-laborsaving-machine",
        "the-rounded-catalogue-divine-complete",
        "book-xxii.-memories-of",
        "my-71st-year",
        "on-the-beach-at-night",
        "song-of-the-redwoodtree",
        "darest-thou-now-o-soul",
        "memories",
        "old-chants",
        "o-tanfaced-prairieboy",
        "turn-o-libertad",
        "vigil-strange-i-kept-on",
        "to-the-leavend-soil-they",
        "the-city-deadhouse",
        "book-xiii",
        "the-dead-emperor",
        "a-woman-waits-for-me",
        "still-though-the-one-i",
        "as-i-walk-these-broad",
        "song-at-sunset",
        "are-you-the-new-person",
        "earth-my-likeness",
        "an-ended-day",
        "the-dalliance-of-the-eagles",
        "i-sit-and-look-out",
        "outlines-for-a-tomb-[g.",
        "quicksand-years",
        "washingtons-monument-february-1885",
        "a-prairie-sunset",
        "with-huskyhaughty-lips-o-sea",
        "soon-shall-the-winters-foil",
        "song-of-the-broadaxe",
        "a-twilight-song",
        "apparitions",
        "behold-this-swarthy-face",
        "book-vii",
        "recorders-ages-hence",
        "one-hour-to-madness-and",
        "song-of-the-exposition",
        "france-[the-18th-year-of",
        "thou-reader",
        "ages-and-ages-returning-at",
        "in-cabind-ships-at-sea",
        "these-carols",
        "abraham-lincoln-born-feb.-12",
        "locations-and-times",
        "a-handmirror",
        "my-legacy",
        "book-xxv",
        "to-thee-old-cause",
        "o-living-always-always-dying",
        "a-childs-amaze",
        "an-old-mans-thought-of",
        "from-paumanok-starting-i-fly",
        "a-riddle-song",
        "patroling-barnegat",
        "america",
        "the-centenarians-story",
        "perfections",
        "gods",
        "book-v.-calamus",
        "night-on-the-prairies",
        "to-a-certain-civilian",
        "yonnondio",
        "what-place-is-besieged",
        "by-the-bivouacs-fitful-flame",
        "???",
        "to-old-age",
        "the-base-of-all-metaphysics",
        "i-saw-in-louisiana-a",
        "halcyon-days",
        "to-the-states-[to-identify",
        "song-of-the-banner-at",
        "a-clear-midnight",
        "when-i-heard-at-the",
        "long-long-hence",
        "to-the-sunset-breeze",
        "my-canary-bird",
        "as-i-ebbd-with-the",
        "this-moment-yearning-and-thoughtful",
        "you-felons-on-trial-in",
        "a-christmas-greeting",
        "as-i-sit-writing-here",
        "o-me-o-life",
        "once-i-passd-through-a",
        "queries-to-my-seventieth-year",
        "of-the-terrible-doubt-of",
        "crossing-brooklyn-ferry",
        "of-that-blithe-throat-of",
        "the-united-states-to-old",
        "the-unexpressd",
        "starting-from-paumanok",
        "the-artillerymans-vision",
        "we-two-boys-together-clinging",
        "to-him-that-was-crucified",
        "shaksperebacons-cipher",
        "by-broad-potomacs-shore",
        "as-consequent-etc.",
        "sometimes-with-one-i-love",
        "old-ireland",
        "old-ages-lambent-peaks",
        "delicate-cluster",
        "long-too-long-america",
        "a-song-of-the-rolling",
        "book-xxi.-drumtaps",
        "a-boston-ballad-[1854]",
        "o-magnetsouth",
        "book-xvi",
        "o-you-whom-i-often",
        "bravo-paris-exposition",
        "o-hymen-o-hymenee",
        "joy-shipmate-joy",
        "others-may-praise-what-they",
        "sail-out-for-good-eidolon",
        "as-if-a-phantom-caressd"
    ]

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        hitDatAPI()
    }
    
    func hitDatAPI(){
//        let urlString : String = "https://pafmon-walt-whitman-poems.p.mashape.com/poems/o-me-o-life"
        let randomIndex: Int = Int(arc4random_uniform(UInt32(arrayOfPoemIndexes.count - 1)))
        print(randomIndex)
        let urlString : String = "https://pafmon-walt-whitman-poems.p.mashape.com/poems/\(arrayOfPoemIndexes[randomIndex])"



        if let url = NSURL(string: urlString){
            let request = NSMutableURLRequest(URL: url)
            request.addValue("application/json", forHTTPHeaderField: "Accept")
            request.addValue("----------", forHTTPHeaderField: "X-Mashape-Key")
            let session = NSURLSession.sharedSession()
            let task = session.dataTaskWithRequest(request){
                (data, response, error) -> Void in
                if let error = error {
                    print(error)
                    return
                } else {
                    let result = String(data: data!, encoding:NSASCIIStringEncoding)!
                    if let resultString = result.dataUsingEncoding(NSUTF8StringEncoding) {
                        do {
                            if let resultDict = try NSJSONSerialization.JSONObjectWithData(resultString, options: []) as? [String:AnyObject]{
                                print(resultDict)
                                self.createXibFromDictionary(resultDict)
                            }
                        } catch let error as NSError {
                            print(error)
                            return
                        }
                    }
                }
            }
            task.resume()
        }
    }
    
    func createXibFromDictionary(dictionary: [String : AnyObject]) {
        
        dispatch_async(dispatch_get_main_queue()) {
            let poemView: PoemView = PoemView.init(frame: CGRect(x: 0, y: 0, width: self.view.frame.width, height: self.view.frame.height))
            
            if let title = dictionary["title"], index = dictionary["index"], text = dictionary["text"] {
                poemView.nameOfPoemTextView.text = title as? String
                poemView.poemTextView.text = text as? String
                
                self.view.addSubview(poemView)
            }
        }
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }


}

